### ISSUE TITLE
Wrong number of samples in the given Google Drive

### ISSUE THREAD

**Issue by zjh21** [SamVadidar/RGBT#1]
Thank you for your great work! 
I downloaded the new cross-labeled FLIR Dataset, and it turned out that there are 7381, 1056 and 2111 samples for train, val and test, which does not match the given number 6924, 1982 and 3960 in your paper. 
I wonder which set is the one you trained and tested RGBT on?

**Comment by SamVadidar** [comment]
Hi @zjh21 
sorry for my late reply. I doubled checked it and the provided dataset in google drive is correct. It might be that I have rearranged the data and cleaned them further, without changing the numbers in the paper draft. But what you have downloaded is what we also used. Sorry for the inconvenience and confusion.
