### ISSUE TITLE
Is it possible to align FLIR_ADAS_V2?

### ISSUE THREAD

**Issue by yiwangwuqianhao** [SamVadidar/RGBT#2]
Is it possible to align FLIR_ADAS_V2?

**Comment by SamVadidar** [comment]
Hi @yiwangwuqianhao 
I did not have a look at the FLIR_ADAS_V2. However, it should be possible to use the  ./FLIR_PP/pp.py and preprocess the data. As far as I know, the data is collected using the same setup, which makes it even easier to align them by the provided code.
